[2025-02-28T09:50:09.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T09:50:09.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-28T09:47:00.692512+00:00 [queued]>
[2025-02-28T09:50:09.585+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-28T09:47:00.692512+00:00 [queued]>
[2025-02-28T09:50:09.586+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-28T09:50:09.595+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): mapreduce> on 2025-02-28 09:47:00.692512+00:00
[2025-02-28T09:50:09.600+0000] {standard_task_runner.py:72} INFO - Started process 184144 to run task
[2025-02-28T09:50:09.601+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'crypto', 'mapreduce', 'manual__2025-02-28T09:47:00.692512+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmpoffemg2g']
[2025-02-28T09:50:09.602+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask mapreduce
[2025-02-28T09:50:09.625+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto.mapreduce manual__2025-02-28T09:47:00.692512+00:00 [running]> on host ali-ThinkBook-14-G2-ITL
[2025-02-28T09:50:09.668+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali rahiqi' AIRFLOW_CTX_DAG_ID='crypto' AIRFLOW_CTX_TASK_ID='mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T09:47:00.692512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T09:47:00.692512+00:00'
[2025-02-28T09:50:09.668+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T09:50:09.680+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-28T09:50:09.680+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'hadoop jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar -D mapreduce.job.num.map.tasks=1 -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=27/coingecko_raw.json -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27 -mapper "/usr/bin/env python3 /home/ali/Desktop/crypto/scripts/mapper.py" -reducer "/usr/bin/env python3 /home/ali/Desktop/crypto/scripts/reducer.py" -file /home/ali/Desktop/crypto/scripts/mapper.py -file /home/ali/Desktop/crypto/scripts/reducer.py']
[2025-02-28T09:50:09.686+0000] {subprocess.py:99} INFO - Output:
[2025-02-28T09:50:10.084+0000] {subprocess.py:106} INFO - 2025-02-28 09:50:10,084 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-28T09:50:10.586+0000] {subprocess.py:106} INFO - packageJobJar: [/home/ali/Desktop/crypto/scripts/mapper.py, /home/ali/Desktop/crypto/scripts/reducer.py, /tmp/hadoop-unjar102255925389383326/] [] /tmp/streamjob17329536097647175994.jar tmpDir=null
[2025-02-28T09:50:10.681+0000] {subprocess.py:106} INFO - 2025-02-28 09:50:10,681 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-28T09:50:10.822+0000] {subprocess.py:106} INFO - 2025-02-28 09:50:10,821 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-28T09:50:10.889+0000] {subprocess.py:106} INFO - 2025-02-28 09:50:10,889 ERROR streaming.StreamJob: Error Launching job : Output directory hdfs://localhost:9000/user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27 already exists
[2025-02-28T09:50:10.890+0000] {subprocess.py:106} INFO - Streaming Command Failed!
[2025-02-28T09:50:11.237+0000] {subprocess.py:110} INFO - Command exited with return code 5
[2025-02-28T09:50:11.241+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-28T09:50:11.244+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=crypto, task_id=mapreduce, run_id=manual__2025-02-28T09:47:00.692512+00:00, execution_date=20250228T094700, start_date=20250228T095009, end_date=20250228T095011
[2025-02-28T09:50:11.263+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T09:50:11.263+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task mapreduce (Bash command failed. The command returned a non-zero exit code 5.; 184144)
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-28T09:50:11.300+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T09:50:11.310+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T09:50:11.318+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
