[2025-02-27T01:02:47.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-27T01:02:47.524+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-27T01:02:32.232063+00:00 [queued]>
[2025-02-27T01:02:47.528+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto.mapreduce manual__2025-02-27T01:02:32.232063+00:00 [queued]>
[2025-02-27T01:02:47.529+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-27T01:02:47.536+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): mapreduce> on 2025-02-27 01:02:32.232063+00:00
[2025-02-27T01:02:47.540+0000] {standard_task_runner.py:72} INFO - Started process 3645183 to run task
[2025-02-27T01:02:47.541+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'crypto', 'mapreduce', 'manual__2025-02-27T01:02:32.232063+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/crypto_dag.py', '--cfg-path', '/tmp/tmpl7g395zj']
[2025-02-27T01:02:47.542+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask mapreduce
[2025-02-27T01:02:47.564+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto.mapreduce manual__2025-02-27T01:02:32.232063+00:00 [running]> on host ali-ThinkBook-14-G2-ITL
[2025-02-27T01:02:47.679+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ali rahiqi' AIRFLOW_CTX_DAG_ID='crypto' AIRFLOW_CTX_TASK_ID='mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T01:02:32.232063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T01:02:32.232063+00:00'
[2025-02-27T01:02:47.680+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-27T01:02:47.687+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-27T01:02:47.688+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        hadoop jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.6.jar         -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=27/coingecko_raw.json         -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=27         -mapper /home/ali/Desktop/crypto/scripts/mapper.py         -reducer /home/ali/Desktop/crypto/scripts/reducer.py         -file /home/ali/Desktop/crypto/scripts/mapper.py         -file /home/ali/Desktop/crypto/scripts/reducer.py']
[2025-02-27T01:02:47.694+0000] {subprocess.py:99} INFO - Output:
[2025-02-27T01:02:48.109+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:48,108 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-27T01:02:48.666+0000] {subprocess.py:106} INFO - packageJobJar: [/home/ali/Desktop/crypto/scripts/mapper.py, /home/ali/Desktop/crypto/scripts/reducer.py, /tmp/hadoop-unjar1434691688072844319/] [] /tmp/streamjob11114453722152201472.jar tmpDir=null
[2025-02-27T01:02:48.754+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:48,754 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-27T01:02:48.846+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:48,846 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
[2025-02-27T01:02:48.983+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:48,983 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/ali/.staging/job_1740561960347_0014
[2025-02-27T01:02:49.180+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,180 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-27T01:02:49.210+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,210 INFO mapreduce.JobSubmitter: number of splits:2
[2025-02-27T01:02:49.323+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,323 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1740561960347_0014
[2025-02-27T01:02:49.323+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,323 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-27T01:02:49.441+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,441 INFO conf.Configuration: resource-types.xml not found
[2025-02-27T01:02:49.441+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,441 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
[2025-02-27T01:02:49.478+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,478 INFO impl.YarnClientImpl: Submitted application application_1740561960347_0014
[2025-02-27T01:02:49.500+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,500 INFO mapreduce.Job: The url to track the job: http://ali-ThinkBook-14-G2-ITL:8088/proxy/application_1740561960347_0014/
[2025-02-27T01:02:49.501+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:49,501 INFO mapreduce.Job: Running job: job_1740561960347_0014
[2025-02-27T01:02:53.553+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:53,552 INFO mapreduce.Job: Job job_1740561960347_0014 running in uber mode : false
[2025-02-27T01:02:53.554+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:53,554 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-27T01:02:56.603+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:56,603 INFO mapreduce.Job: Task Id : attempt_1740561960347_0014_m_000001_0, Status : FAILED
[2025-02-27T01:02:56.615+0000] {subprocess.py:106} INFO - Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:466)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:350)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
[2025-02-27T01:02:56.616+0000] {subprocess.py:106} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:56,615 INFO mapreduce.Job: Task Id : attempt_1740561960347_0014_m_000000_0, Status : FAILED
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-27T01:02:56.617+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:466)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:350)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
[2025-02-27T01:02:56.618+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
[2025-02-27T01:02:56.619+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:02:59.633+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:59,632 INFO mapreduce.Job: Task Id : attempt_1740561960347_0014_m_000000_1, Status : FAILED
[2025-02-27T01:02:59.635+0000] {subprocess.py:106} INFO - Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
[2025-02-27T01:02:59.636+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-27T01:02:59.636+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-27T01:02:59.637+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-27T01:02:59.637+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-27T01:02:59.638+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-27T01:02:59.638+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:466)
[2025-02-27T01:02:59.638+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:350)
[2025-02-27T01:02:59.638+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
[2025-02-27T01:02:59.639+0000] {subprocess.py:106} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-02-27T01:02:59.639+0000] {subprocess.py:106} INFO - 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
[2025-02-27T01:02:59.639+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
[2025-02-27T01:02:59.640+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
[2025-02-27T01:02:59.640+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:02:59.640+0000] {subprocess.py:106} INFO - 2025-02-27 01:02:59,635 INFO mapreduce.Job: Task Id : attempt_1740561960347_0014_m_000001_1, Status : FAILED
[2025-02-27T01:02:59.641+0000] {subprocess.py:106} INFO - Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
[2025-02-27T01:02:59.641+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-27T01:02:59.642+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-27T01:02:59.642+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-27T01:02:59.642+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-27T01:02:59.643+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-27T01:02:59.643+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:466)
[2025-02-27T01:02:59.643+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:350)
[2025-02-27T01:02:59.644+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
[2025-02-27T01:02:59.644+0000] {subprocess.py:106} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-02-27T01:02:59.644+0000] {subprocess.py:106} INFO - 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
[2025-02-27T01:02:59.645+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
[2025-02-27T01:02:59.645+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
[2025-02-27T01:02:59.645+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:03:04.667+0000] {subprocess.py:106} INFO - 2025-02-27 01:03:04,667 INFO mapreduce.Job: Task Id : attempt_1740561960347_0014_m_000000_2, Status : FAILED
[2025-02-27T01:03:04.671+0000] {subprocess.py:106} INFO - Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
[2025-02-27T01:03:04.672+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-27T01:03:04.672+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-27T01:03:04.672+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-27T01:03:04.672+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-27T01:03:04.672+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-27T01:03:04.672+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:466)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:350)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
[2025-02-27T01:03:04.673+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:03:05.676+0000] {subprocess.py:106} INFO - 2025-02-27 01:03:05,676 INFO mapreduce.Job: Task Id : attempt_1740561960347_0014_m_000001_2, Status : FAILED
[2025-02-27T01:03:05.683+0000] {subprocess.py:106} INFO - Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 2
[2025-02-27T01:03:05.684+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-27T01:03:05.684+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-27T01:03:05.684+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-27T01:03:05.684+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-27T01:03:05.684+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:466)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:350)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:178)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)
[2025-02-27T01:03:05.685+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:172)
[2025-02-27T01:03:05.686+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:03:07.698+0000] {subprocess.py:106} INFO - 2025-02-27 01:03:07,698 INFO mapreduce.Job:  map 100% reduce 100%
[2025-02-27T01:03:07.712+0000] {subprocess.py:106} INFO - 2025-02-27 01:03:07,712 INFO mapreduce.Job: Job job_1740561960347_0014 failed with state FAILED due to: Task failed task_1740561960347_0014_m_000000
[2025-02-27T01:03:07.713+0000] {subprocess.py:106} INFO - Job failed as tasks failed. failedMaps:1 failedReduces:0 killedMaps:0 killedReduces: 0
[2025-02-27T01:03:07.714+0000] {subprocess.py:106} INFO - 
[2025-02-27T01:03:07.764+0000] {subprocess.py:106} INFO - 2025-02-27 01:03:07,764 INFO mapreduce.Job: Counters: 14
[2025-02-27T01:03:07.764+0000] {subprocess.py:106} INFO - 	Job Counters
[2025-02-27T01:03:07.764+0000] {subprocess.py:106} INFO - 		Failed map tasks=7
[2025-02-27T01:03:07.764+0000] {subprocess.py:106} INFO - 		Killed map tasks=1
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Killed reduce tasks=1
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Launched map tasks=8
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Other local map tasks=6
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Data-local map tasks=2
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Total time spent by all maps in occupied slots (ms)=13814
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Total time spent by all reduces in occupied slots (ms)=0
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Total time spent by all map tasks (ms)=13814
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Total vcore-milliseconds taken by all map tasks=13814
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		Total megabyte-milliseconds taken by all map tasks=14145536
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 	Map-Reduce Framework
[2025-02-27T01:03:07.765+0000] {subprocess.py:106} INFO - 		CPU time spent (ms)=0
[2025-02-27T01:03:07.766+0000] {subprocess.py:106} INFO - 		Physical memory (bytes) snapshot=0
[2025-02-27T01:03:07.766+0000] {subprocess.py:106} INFO - 		Virtual memory (bytes) snapshot=0
[2025-02-27T01:03:07.766+0000] {subprocess.py:106} INFO - 2025-02-27 01:03:07,764 ERROR streaming.StreamJob: Job not successful!
[2025-02-27T01:03:07.766+0000] {subprocess.py:106} INFO - Streaming Command Failed!
[2025-02-27T01:03:08.120+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-27T01:03:08.125+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-27T01:03:08.128+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto, task_id=mapreduce, run_id=manual__2025-02-27T01:02:32.232063+00:00, execution_date=20250227T010232, start_date=20250227T010247, end_date=20250227T010308
[2025-02-27T01:03:08.167+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-27T01:03:08.167+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task mapreduce (Bash command failed. The command returned a non-zero exit code 1.; 3645183)
Traceback (most recent call last):
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/Desktop/crypto/myenv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-27T01:03:08.178+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-27T01:03:08.253+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-27T01:03:08.253+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
